# Generated by Django 5.2.11 on 2026-03-02 13:44

import learning_logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=learning_logs.models.user_entry_file_path,
                verbose_name="笔记附件",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=learning_logs.models.user_entry_file_path,
                verbose_name="笔记图片",
            ),
        ),
    ]
