# Generated by Django 5.2.12 on 2026-03-08 09:40

import django.db.models.deletion
import learning_logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_attachment_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.CreateModel(
            name='EntryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=learning_logs.models.user_entry_file_path, verbose_name='笔记附件')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='learning_logs.entry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=learning_logs.models.user_entry_file_path, verbose_name='笔记图片')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='learning_logs.entry')),
            ],
        ),
    ]
