# Generated by Django 5.2.12 on 2026-03-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_tag_topic_tags_topic_is_deleted_and_more'),
        ('learning_logs', '0005_remove_entry_attachment_remove_entry_image_and_more'),
    ]

    operations = [
    ]
