# Generated by Django 5.2.12 on 2026-03-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_merge_20260308_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_image_only',
            field=models.BooleanField(default=False, verbose_name='纯图片笔记'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
