# Generated by Django 5.2.12 on 2026-03-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_entryrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='topic',
            name='cover_style',
            field=models.CharField(choices=[('default', '默认渐变'), ('ocean', '海洋蓝'), ('sunset', '日落橙'), ('forest', '森林绿'), ('purple', '梦幻紫'), ('pink', '樱花粉'), ('gold', '金色阳光'), ('dark', '暗夜星空')], default='default', max_length=20, verbose_name='封面样式'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序权重'),
        ),
    ]
