# Generated by Django 5.2.12 on 2026-03-08 11:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_avatar_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='profilealbum',
            name='image',
            field=models.ImageField(upload_to=accounts.models.profile_album_path, verbose_name='相册图片'),
        ),
    ]
